export const PATIENTS_ENDPOINTS = {
    LOGIN:'auth/user/login/',
    SIGNUP: 'auth/user/register/',
    USER: 'users/',
    FORGOT_PASSWORD: 'auth/forgot-password/',
    VERIFY_EMAIL: 'auth/user/verify-code/',
    MOOD: 'track/mood/',
    BLOOD_PRESSURE: 'track/blood-pressure/',
    SLEEP: 'track/sleep/',
    WEIGHT: 'track/weight/',
    MEDICATION: 'track/medication/',
    BOOK_APPOINTMENT: "appointment/consultation/",
    GET_ALL_APPOINTMENT: 'appointment/user/appointments/',
    GET_ALL_HOSPITALS: 'hospital/hospitals',
    GET_ALL_DOCTORS: 'hospital/',
    GET_DOCTOR: 'hospital/doctor/',
    GET_APPOINTMENT: 'appointment/user/',
    CANCEL_APPOINTMENT: 'appointment/user/',
    GET_TRACK_OVERVIEW: 'track/overview',
    CREATE_PROFILE: 'me/profile',
    GET_NOTIFICATIONS: 'notifications/patient',
    UN_READ_NOTIFICATIONS: 'notifications/patient/unread-count',
    READ_ALL_NOTIFICATIONS: 'notifications/patient/read-all',
    GET_SUPPORT: 'support/patient/mine',
    GET_SUPPORT_DETAILS: 'support/patient/',
    GET_ME: 'me',
    CREATE_SUPPORT: 'support/patient',
}
