export const ROUTES = {
    forgotPassword: '/auth/forgot-password',
    login: '/auth/login',
    signup: '/auth/signup',
    reportIssue: '/home/report-issues',
    home: '/home',
    track: '/(tabs)/track',
    consultation: '/(tabs)/consultation',
    messages: '/(tabs)/messages',
    signUpSuccess: '/auth/success',
    about: '/auth/about',
    welcome: '/auth/welcome',
    profile: '/profile',
    settings: '/settings',
    reminder: '/profile/reminder',
    addReminder: '/profile/reminder/add-reminder',
    allReminders: '/home/all-reminders',
    allAppointments: "/consult-screen/all-hospitals",
    doctorsHospitals: '/consult-screen/doctors-hospitals',
    consultationPayment: '/consult-screen/consultation-deatils/payment',
    bloodPressure: '/track-screen/blood-pressure',
    mood: '/track-screen/mood',
    sleep: '/track-screen/sleep-log',
    weight: '/track-screen/weight',
    medication: '/track-screen/medication',
    onnBoarding: '/onboarding',
    allApointments: '/home/all-appointments',
    topRatedDoctors: "/consult-screen/top-rated-doctors",
    bookDoctors: '/consult-screen/consultation-deatils/book-doctor',
    editProfileName: '/profile/edit-name',
    support: '/support'
} as const;

export type RouteValues = typeof ROUTES[keyof typeof ROUTES];
// This creates: '/auth/forgot-password' | '/auth/login' | '/auth/signup'
