export const ADMIN_ENDPOINTS = {
SIGN_UP: 'auth/hospital/register/',
REGISTER: 'auth/hospital/signup/',
LOGIN: 'auth/hospital/login/',
GET_ALL_HOSPITALS: 'hospital/hospitals',
GET_ALL_DOCTORS: 'hospital/doctors',
GET_HOSPITAL_PROFILE: 'hospital/profile',
CREATE_HOSPITAL_PROFILE: 'hospital/profile/',
CREATE_DOCTOR: 'auth/doctor/register/',
GET_ALL_APPOINTMENT: 'appointment/hospital/appointments/',
CREATE_BRANCH: 'hospital/branch',
GET_ALL_BRANCH: 'hospital/branches',
ASSIGN_DOCTOR_TO_BRANCH: 'hospital/branch/assign-doctors',
GET_STATS: "appointment/hospital/stats",
GET_DOCTOR_DETAILS: 'hospital/doctor/',
GET_APPOINTMENT_DETAILS: 'appointment/hospital/',
CREATE_SUPPORT_TICKET: 'support/hospital',
GET_ME: 'hospital/me',
GET_ALL_SUPPORT_PATIEINT: 'support/patient/mine',
GET_NOTIFICATIONS: 'notifications',
UN_READ_NOTIFICATIONS: 'notifications/unread-count',
READ_ALL_NOTIFICATIONS: 'notifications/read-all',
GET_SUPPORT: 'support/hospital/mine',
GET_SUPPORT_DETAILS: 'support/hospital/'
}