export const DOCTOR_ENDPOINTS = {
    LOGIN: 'auth/doctor/login/',
    SIGN_UP: 'auth/doctor/register/',
    REFRESH: 'doctor/token/refresh',
    GET_APPOINTMENT: "appointment/doctor/appointments",
    GET_PAYMENT: 'doctor/earnings/payouts/',
    GET_EARNINGS_SUMMARY: "doctor/earnings/summary/",
    GET_DOCTOR: 'doctor/me',
    CREATE_PROFILE: 'doctor/profile',
    GET_APPOINTMENT_DETAILS: 'appointment/doctor/',
    GET_DOCTOR_AVAILABILITY: 'doctor/availability/me',
    CREATE_DOCTOR_AVAILABILITY: 'doctor/availability',
    APPROVE_APPOINTMENT: 'doctor/',
    REJECT_APPOINTMENT: 'doctor/',
    DOCTOR_PROFILE: '',
    GET_APPOINTMENT_STATS: 'appointment/doctor/stats',
    CREATE_SUPPORT: 'support/doctor',
    GET_SUPPORT: 'support/doctor/mine',
    GET_SUPPORT_DETAILS: 'support/staff/',
    REPLY_TICKET: 'support/staff/',
    GET_NOTIFICATIONS: 'notifications',
    UN_READ_NOTIFICATIONS: 'notifications/unread-count',
    READ_ALL_NOTIFICATIONS: 'notifications/read-all',
}